const products = [
  {
    id: 6,
    name: "Kambing Boer",
    description: "Kambing impor terbaik",
    price: "Rp 4.300.000",
    image: "/boer4.avif",
    type: "boer",
    weight: "20kg",
    age: "6bulan",
  },
  {
    id: 7,
    name: "Kambing Boer",
    description: "Kambing Boer impor terbaik",
    price: "Rp 4.200.000",
    image: "/boer3.avif",
    type: "boer",
    weight: "20kg",
    age: "6bulan",
  },
  {
    id: 8,
    name: "kambing dorper",
    description: "Kambing ternak asli",
    price: "Rp 4.000.000",
    image: "/dorper2.avif",
    type: "dorper",
    weight: "20kg",
    age: "6bulan",
  },
  {
    id: 6,
    name: "Kambing Boer",
    description: "Kambing Boer impor terbaik",
    price: "Rp 4.300.000",
    image: "/boer2.avif",
    type: "boer",
    weight: "20kg",
    age: "6bulan",
  },
  {
    id: 7,
    name: "Kambing Boer",
    description: "Kambing Boer impor terbaik",
    price: "Rp 4.200.000",
    image: "/boer1.avif",
    type: "boer",
    weight: "20kg",
    age: "6bulan",
  },
  {
    id: 8,
    name: "kambing dorper",
    description: "Sapi Brahman asli",
    price: "Rp 4.000.000",
    image: "/dorper.avif",
    type: "dorper",
    weight: "20kg",
    age: "6bulan",
  },
];

export default products;
