const products = [
  {
    id: 6,
    name: "Kambing Boer",
    description: "Kambing terbaik",
    price: "Rp 4.000.000",
    image: "/boer4.avif",
    type: "boer",
    weight: "15kg",
    age: "3-4bulan",
  },
  {
    id: 7,
    name: "Kambing Boer",
    description: "Kambing Boer terbaik",
    price: "Rp 9.000.000",
    image: "/boer3.avif",
    type: "boer",
    weight: "80kg",
    age: "12bulan",
  },
  {
    id: 8,
    name: "kambing dorper",
    description: "Kambing ternak asli",
    price: "Rp 7.000.000",
    image: "/dorper2.avif",
    type: "dorper",
    weight: "80kg",
    age: "12bulan",
  },
  {
    id: 6,
    name: "Kambing Boer",
    description: "Kambing Boer impor terbaik",
    price: "Rp 3.000.000",
    image: "/boer2.avif",
    type: "boer",
    weight: "15kg",
    age: "3-4bulan",
  },
  {
    id: 7,
    name: "Kambing Boer",
    description: "Kambing Boer impor terbaik",
    price: "Rp 9.000.000",
    image: "/boer1.avif",
    type: "boer",
    weight: "80kg",
    age: "12bulan",
  },
  {
    id: 8,
    name: "kambing dorper",
    description: "Kambing dorper",
    price: "Rp 3.000.000",
    image: "/dorper.avif",
    type: "dorper",
    weight: "15kg",
    age: "3-4bulan",
  },
];

export default products;
